# Generated by Django 5.1 on 2024-10-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('card_type', models.CharField(choices=[('hero', 'Herói da Fé'), ('legendary', 'Herói Lendário'), ('sin', 'Pecado'), ('miracle', 'Milagre'), ('artfacts', 'Artefatos'), ('wisdon', 'Sabedoria')], default='hero', max_length=25)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='cards')),
                ('card_image_mini', models.ImageField(blank=True, null=True, upload_to='cards')),
                ('card_description', models.CharField(default='', max_length=250)),
                ('session', models.CharField(choices=[('alpha', 'Alpha'), ('genesis', 'Gênesis')], max_length=25)),
                ('slug', models.CharField(db_index=True, max_length=30, unique=True)),
                ('wisdom_cost', models.IntegerField(default=0)),
                ('attack_point', models.IntegerField(default=0)),
                ('defense_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games')),
            ],
        ),
    ]
