# Generated by Django 5.1 on 2024-08-29 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.CharField(db_index=True, max_length=30, unique=True)),
                ('wisdom_cost', models.IntegerField(default=0)),
                ('attack_point', models.IntegerField(default=0)),
                ('defense_points', models.IntegerField(default=0)),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='player_site.cardsession')),
            ],
        ),
    ]
