# Generated by Django 5.1 on 2024-10-24 22:29

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='avatar',
            field=models.CharField(blank=True, choices=users.models.getAvatarChoices, null=True),
        ),
    ]
