services:
  site:
    container_name: site
    build: ./
    restart: always
    volumes:
    # Faith Battle static content
      - ./static:/api/static
      # - type: bind
      #   source: /home/marcos/dockers/Faith_Battle_Site/static/
      #   target: /api/static
    # Faith Battle media content
      - ./media:/api/media
      # - type: bind
      #   source: /home/marcos/dockers/Faith_Battle_Site/media/
      #   target: /api/media
    # Nginx Sockets access
      - type: bind
        source: /home/marcos/dockers/sockets/
        target: /api/sockets
