# Generated by Django 5.1 on 2024-10-10 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('img_capa', models.ImageField(blank=True, null=True, upload_to='artigos/<django.db.models.fields.AutoField>')),
                ('img_descricao', models.ImageField(blank=True, null=True, upload_to='artigos/<django.db.models.fields.AutoField>')),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('conteudo', models.TextField()),
                ('tag_version', models.CharField(max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
