# Generated by Django 5.1 on 2024-11-04 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destaque', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=255)),
                ('img_capa', models.ImageField(blank=True, null=True, upload_to='artigos/')),
                ('data_hora_publicacao', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('conteudo', models.TextField()),
                ('tag_version', models.CharField(max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enquetes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_hora_publicacao', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('max_dias', models.IntegerField(blank=True, default=7, null=True)),
                ('min_votos_por_opcao', models.IntegerField(blank=True, default=50, null=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('apoia', models.IntegerField(blank=True, default=0)),
                ('nao_apoia', models.IntegerField(blank=True, default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
