# Generated by Django 5.1 on 2024-10-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='data_publicacao',
        ),
        migrations.AddField(
            model_name='artigo',
            name='data_hora_publicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='img_capa',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='img_descricao',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/'),
        ),
    ]
