# Generated by Django 5.1 on 2024-10-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novidades', '0003_remove_artigo_img_descricao_artigo_destaque_enquetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquetes',
            name='apoia',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='enquetes',
            name='nao_apoia',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
