# Generated by Django 5.1 on 2024-10-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novidades', '0005_uploadimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimages',
            name='_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadimages',
            name='_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
