# Generated by Django 5.1 on 2024-10-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novidades', '0006_uploadimages__path_uploadimages__url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImages',
        ),
    ]
