# Generated by Django 5.1 on 2024-10-23 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novidades', '0007_delete_uploadimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='data_hora_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 23, 16, 38, 1, 24448, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
