# Generated by Django 5.1 on 2024-10-23 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novidades', '0009_alter_artigo_data_hora_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='data_hora_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 23, 16, 43, 24, 810484, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
