# Generated by Django 5.1 on 2024-10-23 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novidades', '0013_alter_artigo_data_hora_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquetes',
            name='data_hora_publicacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
