# Generated by Django 5.1 on 2024-11-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bottom_left_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='bottom_right_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='top_left_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='top_right_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cardfamily',
            name='card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
