# Generated by Django 5.1 on 2024-10-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gameboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFamily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('card_back_image', models.ImageField(blank=True, null=True, upload_to='cards')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
