# Generated by Django 5.1 on 2024-10-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
