# Generated by Django 5.1 on 2024-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_card_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='attack_point',
            new_name='bottom_left_value',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='defense_points',
            new_name='bottom_right_value',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='wisdom_cost',
            new_name='top_left_value',
        ),
        migrations.AddField(
            model_name='card',
            name='bottom_left_txt',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='bottom_right_txt',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='top_left_txt',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='top_right_txt',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='top_right_value',
            field=models.IntegerField(default=0),
        ),
    ]
