# Generated by Django 5.1 on 2024-10-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_attack_point_card_bottom_left_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='bottom_left_txt',
        ),
        migrations.RemoveField(
            model_name='card',
            name='bottom_right_txt',
        ),
        migrations.RemoveField(
            model_name='card',
            name='top_left_txt',
        ),
        migrations.RemoveField(
            model_name='card',
            name='top_right_txt',
        ),
        migrations.AddField(
            model_name='cardfamily',
            name='bottom_left_txt',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardfamily',
            name='bottom_right_txt',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardfamily',
            name='top_left_txt',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardfamily',
            name='top_right_txt',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
