# Generated by Django 5.1 on 2024-10-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_card_bottom_left_txt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfamily',
            name='deck_position_X',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardfamily',
            name='deck_position_Y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
